MFVI:
  hexa_rank: 150
  hexa_std: 1
  iterations: 3
  normalize_weight: true
  quad_rank: 150
  quad_std: 1
  tag_dim: 150
  use_hexalinear: false
  use_quadrilinear: false
  use_second_order: false
  use_third_order: false
  window_size: 1
ModelFinetuner:
  distill_mode: false
  sentence_level_batch: true
anneal_factor: 2
embeddings:
  TransformerWordEmbeddings-0:
    doc_batch_size: 2
    fine_tune: true
    layers: '-1'
    model: microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext
    pooling_operation: first
interpolation: 0.5
is_teacher_list: true
model:
  FastSequenceTagger:
    crf_attention: true
    dropout: 0.1
    hidden_size: 256
    locked_dropout: 0.0
    remove_x: true
    sentence_loss: true
    use_cnn: false
    use_crf: true
    use_rnn: false
    word_dropout: 0
model_name: BC5CDRchem
ner:
  ColumnCorpus-AnatEM:
    column_format:
      0: text
      1: ner
    data_folder: /content/drive/MyDrive/CLNER/datasets/MTL-Bioinformatics-2016/AnatEM-IOB
    tag_to_bioes: ner
  ColumnCorpus-BC5CDRchem:
      column_format:
        0: text
        1: ner
      data_folder: /content/drive/MyDrive/CLNER/datasets/MTL-Bioinformatics-2016/BC5CDR-chem-IOB
      tag_to_bioes: ner
  ColumnCorpus-BC5CDRdisease:
      column_format:
        0: text
        1: ner
      data_folder: /content/drive/MyDrive/CLNER/datasets/MTL-Bioinformatics-2016/BC5CDR-IOB
      tag_to_bioes: ner
  ColumnCorpus-BioNLP09:
      column_format:
        0: text
        1: ner
      data_folder: /content/drive/MyDrive/CLNER/datasets/MTL-Bioinformatics-2016/BioNLP09-IOB
      tag_to_bioes: ner
  ColumnCorpus-BioNLP11EPI:
      column_format:
        0: text
        1: ner
      data_folder: /content/drive/MyDrive/CLNER/datasets/MTL-Bioinformatics-2016/BioNLP11EPI-IOB
      tag_to_bioes: ner
  ColumnCorpus-BioNLP11IDchem:
      column_format:
        0: text
        1: ner
      data_folder: /content/drive/MyDrive/CLNER/datasets/MTL-Bioinformatics-2016/BioNLP11ID-chem-IOB
      tag_to_bioes: ner
  ColumnCorpus-BioNLP11IDggp:
      column_format:
        0: text
        1: ner
      data_folder: /content/drive/MyDrive/CLNER/datasets/MTL-Bioinformatics-2016/BioNLP11ID-ggp-IOB
      tag_to_bioes: ner
  ColumnCorpus-BioNLP11ID:
      column_format:
        0: text
        1: ner
      data_folder: /content/drive/MyDrive/CLNER/datasets/MTL-Bioinformatics-2016/BioNLP11ID-IOB
      tag_to_bioes: ner
  ColumnCorpus-BioNLP11ID-species:
      column_format:
        0: text
        1: ner
      data_folder: /content/drive/MyDrive/CLNER/datasets/MTL-Bioinformatics-2016/BioNLP11ID-species-IOB
      tag_to_bioes: ner
  ColumnCorpus-BioNLP13CGcc:
      column_format:
        0: text
        1: ner
      data_folder: /content/drive/MyDrive/CLNER/datasets/MTL-Bioinformatics-2016/BioNLP13CG-cc-IOB
      tag_to_bioes: ner
  ColumnCorpus-BioNLP13CGcell:
      column_format:
        0: text
        1: ner
      data_folder: /content/drive/MyDrive/CLNER/datasets/MTL-Bioinformatics-2016/BioNLP13CG-cell-IOB
      tag_to_bioes: ner
  ColumnCorpus-BioNLP13CGchem:
      column_format:
        0: text
        1: ner
      data_folder: /content/drive/MyDrive/CLNER/datasets/MTL-Bioinformatics-2016/BioNLP13CG-chem-IOB
      tag_to_bioes: ner
  ColumnCorpus-BioNLP13CGggp:
      column_format:
        0: text
        1: ner
      data_folder: /content/drive/MyDrive/CLNER/datasets/MTL-Bioinformatics-2016/BioNLP13CG-ggp-IOB
      tag_to_bioes: ner
  ColumnCorpus-BioNLP13CG:
      column_format:
        0: text
        1: ner
      data_folder: /content/drive/MyDrive/CLNER/datasets/MTL-Bioinformatics-2016/BioNLP13CG-IOB
      tag_to_bioes: ner
  ColumnCorpus-BioNLP13CGspecies:
      column_format:
        0: text
        1: ner
      data_folder: /content/drive/MyDrive/CLNER/datasets/MTL-Bioinformatics-2016/BioNLP13CG-species-IOB
      tag_to_bioes: ner
  ColumnCorpus-BioNLP13GE:
      column_format:
        0: text
        1: ner
      data_folder: /content/drive/MyDrive/CLNER/datasets/MTL-Bioinformatics-2016/BioNLP13GE-IOB
      tag_to_bioes: ner
  ColumnCorpus-BioNLP13PCcc:
      column_format:
        0: text
        1: ner
      data_folder: /content/drive/MyDrive/CLNER/datasets/MTL-Bioinformatics-2016/BioNLP13PC-cc-IOB
      tag_to_bioes: ner
  ColumnCorpus-BioNLP13PCchem:
      column_format:
        0: text
        1: ner
      data_folder: /content/drive/MyDrive/CLNER/datasets/MTL-Bioinformatics-2016/BioNLP13PC-chem-IOB
      tag_to_bioes: ner
  ColumnCorpus-BioNLP13PCggp:
      column_format:
        0: text
        1: ner
      data_folder: /content/drive/MyDrive/CLNER/datasets/MTL-Bioinformatics-2016/BioNLP13PC-ggp-IOB
      tag_to_bioes: ner
  ColumnCorpus-BioNLP13PC:
      column_format:
        0: text
        1: ner
      data_folder: /content/drive/MyDrive/CLNER/datasets/MTL-Bioinformatics-2016/BioNLP13PC-IOB
      tag_to_bioes: ner
  ColumnCorpus-CRAFTcc:
      column_format:
        0: text
        1: ner
      data_folder: /content/drive/MyDrive/CLNER/datasets/MTL-Bioinformatics-2016/CRAFT-cc-IOB
      tag_to_bioes: ner
  ColumnCorpus-CRAFTcell:
      column_format:
        0: text
        1: ner
      data_folder: /content/drive/MyDrive/CLNER/datasets/MTL-Bioinformatics-2016/CRAFT-cell-IOB
      tag_to_bioes: ner
  ColumnCorpus-CRAFTchem:
      column_format:
        0: text
        1: ner
      data_folder: /content/drive/MyDrive/CLNER/datasets/MTL-Bioinformatics-2016/CRAFT-chem-IOB
      tag_to_bioes: ner
  ColumnCorpus-CRAFTggp:
      column_format:
        0: text
        1: ner
      data_folder: /content/drive/MyDrive/CLNER/datasets/MTL-Bioinformatics-2016/CRAFT-ggp-IOB
      tag_to_bioes: ner
  ColumnCorpus-CRAFT:
      column_format:
        0: text
        1: ner
      data_folder: /content/drive/MyDrive/CLNER/datasets/MTL-Bioinformatics-2016/CRAFT-IOB
      tag_to_bioes: ner
  ColumnCorpus-CRAFTspecies:
      column_format:
        0: text
        1: ner
      data_folder: /content/drive/MyDrive/CLNER/datasets/MTL-Bioinformatics-2016/CRAFT-species-IOB
      tag_to_bioes: ner
  ColumnCorpus-ExPTM:
      column_format:
        0: text
        1: ner
      data_folder: /content/drive/MyDrive/CLNER/datasets/MTL-Bioinformatics-2016/Ex-PTM-IOB
      tag_to_bioes: ner
  ColumnCorpus-linnaeus:
      column_format:
        0: text
        1: ner
      data_folder: /content/drive/MyDrive/CLNER/datasets/MTL-Bioinformatics-2016/linnaeus-IOB
      tag_to_bioes: ner
  Corpus: ColumnCorpus-BC5CDRchem
  tag_dictionary: resources/taggers/aug_BC5CDRchem_ner_tags.pkl
target_dir: resources/taggers/
targets: ner
teacher_annealing: false
train:
  embeddings_storage_mode: none
  fine_tune_mode: false
  gradient_accumulation_steps: 2
  learning_rate: 5.0e-05
  lr_rate: 10000
  max_epochs: 60
  mini_batch_size: 64
  monitor_test: false
  save_final_model: false
  train_with_dev: false
  true_reshuffle: false
  use_warmup: false
trainer: ModelFinetuner